spring:
  datasource:
    username: root
    password: 9786
    url: jdbc:mysql://localhost:3306/ies
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
